# حافظه JVM مربوط به Gradle؛ برای Build پروژه Compose فضای کافی فراهم می‌کند.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# استفاده از AndroidX برای کتابخانه‌های مدرن Android.
android.useAndroidX=true

# سبک رسمی Kotlin برای قالب‌بندی و رفتار پیش‌فرض کامپایلر.
kotlin.code.style=official

# R class کوچک‌تر باعث Build سریع‌تر و خروجی تمیزتر می‌شود.
android.nonTransitiveRClass=true
